export const GET_NOTIFICATIONS = 'GET_NOTIFICATIONS';
export const GET_NOTIFICATIONS_FULFILLED = `${GET_NOTIFICATIONS}_FULFILLED`;
export const GET_NOTIFICATIONS_REJECTED = `${GET_NOTIFICATIONS}_REJECTED`;
export const GET_NOTIFICATIONS_PENDING = `${GET_NOTIFICATIONS}_PENDING`;
export const GET_NOTIFICATIONS_RESET = `${GET_NOTIFICATIONS}_RESET`;


// Errors
export const ERROR_HTTP = 'ERROR_HTTP';
export const ERROR_HTTP_UNAUTHORIZED = 'ERROR_HTTP_UNAUTHORIZED';
export const ERROR_HTTP_FORBIDDEN = 'ERROR_HTTP_FORBIDDEN';
export const ERROR_HTTP_INTERNAL_SERVER_ERROR = 'ERROR_HTTP_INTERNAL_SERVER_ERROR';
export const ERROR_HTTP_NETWORK = 'ERROR_HTTP_NETWORK';
export const ERROR_HTTP_TIMEOUT = 'ERROR_HTTP_TIMEOUT';
